version: '3' # versao do docker compose
services: # servicos que vamos utilizar no docker compose (servidor web, frontend, backend, banco de dados, etc)
  frontend: # nome do servico
    container_name: frontend # nome do container
    build: frontend/ # pasta onde esta o dockerfile
    restart: on-failure # reinicia o servico caso ele falhe (nao e recomendado para banco de dados)
    depends_on: # depende do servico backend
      - backend
    ports: # porta que o servico vai utilizar (3000:3000) porta do host: porta do servico 
      - 3000:3000
  backend:
    container_name: backend
    build: backend/ 
    restart: on-failure
    depends_on:
      - database
    ports:
      - 3001-3001
    environment: # variaveis de ambiente que o servico vai utilizar 
      - DB_HOST=database # nome do servico do banco de dados
      - DB_USER=postgres # usuario do banco de dados (postgres) o postegres é o usuario padrao do banco de dados
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: unless-stopped 

# o compose possui quatro politicas de reinicio de servico, sendo elas:
# on-failure - reinicia o servico caso ele falhe (nao e recomendado para banco de dados)
# no - nunca reinicia o servico (padrao)  esse servico é recomendado para banco de dados  
# always - sempre reinicia o servico caso ele pare de funcionar (recomendado para banco de dados)
# unless-stopped - reinicia o servico caso ele pare de funcionar (recomendado para banco de dados) a menos que o usuario pare o servico manualmente 


